### ISSUE TITLE
composer.json requires dev-master of zendframework

### ISSUE THREAD

**Issue by jeremiahsmall** [bjyoungblood/BjyProfiler#10]
Probably need to modify the composer.json requirement for dev-master now

```
"zendframework/zendframework": "dev-master"
```

should be updated to be (I think)

```
"zendframework/zendframework": ">=2.0.0"
```

Currently if you include it by packagist, it forces you to make zendframework dev-master, which is now tracking as 2.0.1

**Comment by bjyoungblood** [comment]
@dVaffection I just pushed 614e87ed8de22f8b628fe4fd4ffad6d04e8b339e -- should fix your issue.

**Comment by DmitryVarennikov** [comment]
Yep, sorry meanwhile I created new issue for that  https://github.com/bjyoungblood/BjyProfiler/issues/12
