### ISSUE TITLE
Module (BjyProfiler) could not be initialized.

### ISSUE THREAD

**Issue by DmitryVarennikov** [bjyoungblood/BjyProfiler#12]
Steps to reproduce:
- Add "bjyoungblood/bjy-profiler": "dev-master" to composer.json
- executed update command: php composer.phar update to download vendor
- Add BjyProfiler to modules list in config/application.config.php 

Result  exception: **Zend\ModuleManager\Exception\RuntimeException: Module (BjyProfiler) could not be initialized.**

Can't understand the reason and wasn't able tot google anything!

**Comment by bjyoungblood** [comment]
Try running `php composer.phar update` now. 614e87ed8de22f8b628fe4fd4ffad6d04e8b339e should fix this issue.

**Comment by DmitryVarennikov** [comment]
Yep, everything works now!
By the way are you planning to add queries to the toolbar (not only time and quantity)?

**Comment by bjyoungblood** [comment]
I thought about it, but I'm not really sure how it would work, especially if you have a lot of queries. In my applications, I've just been adding this view partial to my layout:

https://gist.github.com/3725712
And here's the view helper to go with it: https://gist.github.com/3725715
And the service manager config (to go in Module.php): https://gist.github.com/3725720

**Comment by DmitryVarennikov** [comment]
I like how it's done in ZF1 debug toolbar [ZFDebug](http://code.google.com/p/zfdebug/) I noticed they moved to [Github](https://github.com/jokkedk/ZFDebug) and slightly changed appearance of the toolbar but I guess idea remains the same.

**Comment by DmitryVarennikov** [comment]
Thanks for helper. I moved call of the view script to the view helper and helper itself call in the layout 

``` php
<? if ('development' == getenv('APPLICATION_ENV')) : ?>
    <?=$this->dbQueryProfiles()?>
<? endif; ?>
```
