### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by DmitryVarennikov** [bjyoungblood/BjyProfiler#15]
Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in /var/www/project/vendor/zendframework/zend-developer-tools/src/ZendDeveloperTools/Profiler.php on line 217

Not certain whose bug it is. Especially considering to this `$this->report->addCollector(unserialize(serialize($collector)));` in [ZendDeveloperTools\Profiler](https://github.com/zendframework/ZendDeveloperTools/blob/master/src/ZendDeveloperTools/Profiler.php) line **217**

**Comment by atukai** [comment]
I got the same error: Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in ZendDeveloperTools/Collector/DbCollector.php:141 Stack trace: #0 ZendDeveloperTools/Collector/DbCollector.php(141): serialize(Object(BjyProfiler\Db\Profiler\Profiler))

**Comment by bjyoungblood** [comment]
Does this problem occur prior to commit 08edcfb2e37cc8a179f1b16001b0857a5fe94b0a?

**Comment by DmitryVarennikov** [comment]
Hard to say it's been a long time since I updated it last time.

**Comment by ihordev** [comment]
I think that problem happened after you have updated package ZendDeveloperTools

**Comment by DmitryVarennikov** [comment]
@ihordev Maybe. That's why I said I'm not certain whom this bug belongs to. I hope @bjyoungblood will figure out that.

**Comment by sven-tappert** [comment]
I get same error message, but only when user tries to login (user data is written to session). It seems that one must not use a closure in the configuration setup.

So I use the (already existing) ProfilingAdapterFactory instead in my setup:

``` php
<?php

$dbParams = array(
    'database'  => 'changeme',
    'username'  => 'changeme',
    'password'  => 'changeme',
    'hostname'  => 'localhost',
    // buffer_results - only for mysqli buffered queries, skip for others
    'options' => array('buffer_results' => true)
);

return array(

    // Default DB setup
    'db' => array(
        'driver'    => 'Pdo',
        'dsn'       => 'mysql:dbname='.$dbParams['database'].';host='.$dbParams['hostname'].';charset=utf8',
        'database'  => $dbParams['database'],
        'hostname'  => $dbParams['hostname'],
        'user'      => $dbParams['username'],
        'password'  => $dbParams['password'],
    ),

    // Setup for BjyProfiler
    'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => 'BjyProfiler\Db\Adapter\ProfilingAdapterFactory',
        ),
    ),
);
```
