### ISSUE TITLE
ZF 2.1: Declaration of BjyProfiler\Db\Adapter\ProfilingAdapter::setProfiler() 

### ISSUE THREAD

**Issue by atans** [bjyoungblood/BjyProfiler#21]
Fatal error: Declaration of BjyProfiler\Db\Adapter\ProfilingAdapter::setProfiler() must be compatible with that of Zend\Db\Adapter\Profiler\ProfilerAwareInterface::setProfiler() in E:\web\whatsapp\vendor\BjyProfiler\src\BjyProfiler\Db\Adapter\ProfilingAdapter.php on line 9

**Comment by debugger84** [comment]
I have done changes in my local copy of this module to work with Zend 2.1. 

In class BjyProfiler\Db\Adapter\ProfilingAdapter I added 
use Zend\Db\Adapter\Profiler\ProfilerInterface;
Also I changed defination of method setProfiler to setProfiler(ProfilerInterface $p)

In class BjyProfiler\Db\Profiler\Profiler I added two methods

/**
     \* @param string|\Zend\Db\Adapter\StatementContainerInterface $target
     \* @return mixed
     */
    public function profilerStart($target)
    {
        $sql = $target->getSql();
        $params = $target->getParameterContainer();
        $this->startQuery($sql, $params);
    }

```
public function profilerFinish()
{
    // TODO: Implement profilerFinish() method.
}
```

And in class BjyProfiler\Db\Adapter\Driver\Pdo\ProfilingStatement I changed defination of  method setProfiler() to public function setProfiler(ProfilerInterface $p)

**Comment by localheinz** [comment]
@debugger84 Can you issue a PR?

**Comment by intellix** [comment]
Also add 
use Zend\Db\Adapter\Profiler\ProfilerInterface;

at the top of ProfilingStatement

**Comment by cbergau** [comment]
A pull request would be nice. Can't use BjyProfiler anymore :-(

**Comment by localheinz** [comment]
You could still fix the ZF version to 2.0.7 in composer.json or however you manage your dependencies. The signature has only been changed for 2.1.

**Comment by internalsystemerror** [comment]
For those wanting to be able to use BjyProfiler with ZF 2.1 before this is fixed, you can use the following in your project's composer.json:

```
"repositories": [
    {
        "type": "vcs",
        "url": "git://github.com/internalsystemerror/BjyProfiler.git"
    }
],
"require": {
    "php": ">=5.3",
    "zendframework/zendframework": ">=2.1",
    "zendframework/zend-developer-tools": "dev-master",
    "bjyoungblood/bjy-profiler": "dev-hotfix/issue-21"
},
```

Hope that helps for now.

**Comment by internalsystemerror** [comment]
This has now been fixed.
