### ISSUE TITLE
Viewing queries inside toolbar

### ISSUE THREAD

**Issue by webdevilopers** [bjyoungblood/BjyProfiler#23]
It would be nice to view the queries inside the toolbar's container similar to the Doctrine profiler.

Denis Ryabov posted a solution for this inside the toolbars template:
http://stackoverflow.com/questions/13275569/how-to-view-db-queries-generated-by-tablegateway-in-zend-framework-2

Is it possible?

**Comment by bjyoungblood** [comment]
Possible, I'm sure. I unfortunately don't have the time for such a task. Here are a couple of snippets that might help you out:

[View partial](https://gist.github.com/bjyoungblood/3725712)
[View helper](https://gist.github.com/bjyoungblood/3725715)
[View helper service config](https://gist.github.com/bjyoungblood/3725720)

**Comment by vgarvardt** [comment]
I dug into that feature and found that it is not related to Profiler module. This is related to ZendDeveloperTools, that checks if this module is installed and uses its information. If someone is interested in this feature - look at [my pull request](https://github.com/zendframework/ZendDeveloperTools/pull/70) that adds queries list and details to ZendDeveloperTools DB toolbar

**Comment by joshribakoff** [comment]
The toolbar already has this feature, this ticket should be closed.

**Comment by webdevilopers** [comment]
I can see this feature activated for Doctrine but where Do I find the queries for Zend\Db, @joshribakoff ?

**Comment by joshribakoff** [comment]
Same place. See my app here http://demo.metator.com - no doctrine in sight yet the DB panel is populated. Anyways this has nothing to do with bjyProfiler. This conversation belongs on the ZendDeveloperTools repository! bjy is not responsbile for integrating his code into other projects, those projects are responsible for integrating it themselves so please move this conversation there, or fee free to email for help.

**Comment by webdevilopers** [comment]
Sure, @joshribakoff . I just missing the update for my ZendDevelopTools! :)
