### ISSUE TITLE
Queries count is doubled

### ISSUE THREAD

**Issue by vgarvardt** [bjyoungblood/BjyProfiler#26]
It was very interesting for me why there are so many queries on my pages so I implemented simple queries list browser using code from http://stackoverflow.com/questions/13275569/how-to-view-db-queries-generated-by-tablegateway-in-zend-framework-2 and I found that it shows all queries twice. First one has source (stack trace) and the second one always has execution time = 0 and empty stack trace.

Here is picture of my current queries list panel (it's ugly but better than nothing) with doubled queries http://i.imgur.com/AQ8C5Oq.png

Here is gist https://gist.github.com/vgarvardt/5133500 with patched db panel (and styles) so you could try it live (and maybe use as a base for much-wanted and long-waited #23 implementation)

**Comment by bjyoungblood** [comment]
Is `$this->collector->getQueryCount()` correct, or is that doubled as well?

**Comment by vgarvardt** [comment]
Doubled as well - queries count in the panel matches displayed queries list. For the page I'm working on now it shows 14 Read queries, lists 14 queries but only 7 of them are real queries.

**Comment by bjyoungblood** [comment]
Hmm. Do the duplicate queries have the same stack trace? If so, then it seems it's probably something internal that's leading them to be added twice to the list of profiles.

**Comment by vgarvardt** [comment]
They have empty stack trace and 0 execution time.

**Comment by bjyoungblood** [comment]
Fixed by #28
