### ISSUE TITLE
UTF8 encoding using PDO

### ISSUE THREAD

**Issue by jroedel** [bjyoungblood/BjyProfiler#36]
I spent 2 hours trying to figure out how to configure my db connection for UTF8 encoding.  I figured it out, but I suggest adding a 'driver_options' element to the configuration array in the Readme.md:

$dbParams = array(
    'database'  => 'changeme',
    'username'  => 'changeme',
    'password'  => 'changeme',
    'hostname'  => 'localhost',
    // buffer_results - only for mysqli buffered queries, skip for others
    'options' => array('buffer_results' => true),
    'driver_options' => array() //!!!!!!!!!!!!!!!!! here and....
);

return array(
    'service_manager' => array(
        'factories' => array(
            'Zend\Db\Adapter\Adapter' => function ($sm) use ($dbParams) {
                $adapter = new BjyProfiler\Db\Adapter\ProfilingAdapter(array(
                    'driver'    => 'pdo',
                    'dsn'       => 'mysql:dbname='.$dbParams['database'].';host='.$dbParams['hostname'],
                    'database'  => $dbParams['database'],
                    'username'  => $dbParams['username'],
                    'password'  => $dbParams['password'],
                    'hostname'  => $dbParams['hostname'],
                    'driver_options' => $dbParams['driver_options'],  // HERE !!!!!!!!!!!!!!!!
                ));

//....

The option by the way is:

```
    'driver_options'   =>  array(
        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES UTF8'
    )
```

Thanks.

**Comment by bjyoungblood** [comment]
Good info, but it applies to `Zend\Db` itself rather than this module.
