### ISSUE TITLE
Incompatible with ZF 2.3

### ISSUE THREAD

**Issue by knstntndmdnkv** [bjyoungblood/BjyProfiler#45]
\BjyProfiler\Db\Adapter\ProfilingAdapter is no longer compatible with Zend Framework 2.3

This error happened after update from 2.2.x to 2.3

Strict standards: Declaration of BjyProfiler\Db\Adapter\ProfilingAdapter::query() should be compatible with Zend\Db\Adapter\Adapter::query($sql, $parametersOrQueryMode = 'prepare', Zend\Db\ResultSet\ResultSetInterface $resultPrototype = NULL) in \vendor\bjyoungblood\bjy-profiler\src\BjyProfiler\Db\Adapter\ProfilingAdapter.php on line 11

**Comment by ojhaujjwal** [comment]
@hakd I got the same error while upgrading ZF2 from 2.2.5 to 2.3.0

**Comment by Ponsjuh** [comment]
Should be fixed in commit 45d1614cb but Packagist still needs to update to this last commit. Packagist points to dev-master reference: 1ad040a

**Comment by stijnhau** [comment]
Hope they fix will be merged soon because its anaoying that direct after install you need to look after fixes.

**Comment by ojhaujjwal** [comment]
@stijnhau This is already fixed. Use `dev-master`!

**Comment by bjyoungblood** [comment]
I added a 1.1.0 tag with the recent fixes/updates so you don't have to change minimum-stability.

**Comment by stijnhau** [comment]
Any idea how long it will take for packagist to add the new version to composer?

**Comment by bjyoungblood** [comment]
Should be up to date now. Just change your composer.json to point to `v1.1.0` and run `php composer.phar update`
