### ISSUE TITLE
Module (bjyoungblood/bjy-profiler) could not be initialized

### ISSUE THREAD

**Issue by maegnes** [bjyoungblood/BjyProfiler#48]
Hi,

i've tried to install the profiler via composer with the following content:

```
"require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "dev-master",
        "zendframework/zend-developer-tools": "dev-master",
        "zf-commons/zfc-user": "dev-master",
        "zendframework/zftool": "dev-master",
        "bjyoungblood/bjy-profiler" : "dev-master"
    }
```

I've also tried it with zendframework stable 2.3.0 and bjy-profiler version 1.1.0 - didn't work though. After adding the module to my application.config.php, the following error appears:

```
Zend\ModuleManager\Exception\RuntimeException: Module (bjyoungblood/bjy-profiler) could not be initialized.
```

I read the existing issues to that error in the issues list, but couldn't figure out why it is not working for my setup.

thx in advance for some hints
magnus

**Comment by abidi** [comment]
same problem here !

**Comment by abidi** [comment]
first of all look at  this issue 'Module (BjyProfiler) could not be initialized. #12 ' 
second  look here : http://stackoverflow.com/questions/24031446/enabling-bjyprofiler-module-in-zend-framework-2
it work fine for me I hope so for you :)
