### ISSUE TITLE
Use of undefined constant

### ISSUE THREAD

**Issue by ashireman** [bjyoungblood/BjyProfiler#6]
Notice: Use of undefined constant DEBUG_BACKTRACE_IGNORE_ARGS - assumed 'DEBUG_BACKTRACE_IGNORE_ARGS' in \vendor\bjyoungblood\BjyProfiler\src\BjyProfiler\Db\Adapter\Driver\Pdo\ProfilingStatement.php on line 24

**Comment by coss** [comment]
That is because the current min. version is PHP 5.3.6, because of that.
