### ISSUE TITLE
Issue with zend framework 3

### ISSUE THREAD

**Issue by marashlyansuren** [bjyoungblood/BjyProfiler#66]
I hae zend framework 3 and by dependencies zendframework/zend-code 3.1.0 but your package not  satisfiable with that. See composer output attachment
![selection_004](https://user-images.githubusercontent.com/3089635/30844393-e587b76e-a29f-11e7-93c7-066434c38901.png)

**Comment by halfpastfouram** [comment]
Almost a year later but no reply. This issue means a lot of people with up-to-date ZF3 installations can't use this plugin anymore. We had to stop using it as well.

**Comment by chris-kruining** [comment]
@halfpastfouram did you perhaps find a suitable alternative? otherwise I'll implement is myself...

**Comment by bartko-s** [comment]
@chris-kruining. Try my implementation [here](https://github.com/bartko-s/stefano-db-profiler). It is marked as deprecated but should work with newest version of Zend Framework.

**Comment by bioub** [comment]
Just install master branch : `composer require bjyoungblood/bjy-profiler:dev-master`

**Comment by grzegorz-wawrzak-ams** [comment]
@bioub It gives another error: `Module (BjyProfiler) could not be initialized.`
